version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      DATABASE_FILENAME: /app/data.db
      APP_KEYS: change_me
      CLIENT_URL: http://localhost:3000
    ports:
      - '1337:1337'
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      BACKEND_URL: http://localhost:1337
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  db-data:
